// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkdpbljatiemnfoxfbqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrZHBibGphdGllbW5mb3hmYnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTExMzcsImV4cCI6MjA3MTg4NzEzN30.y2wASVdVZMr2Gy97q-7KhV-BE2Qm3Lp1mFmRzshK8s8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});